  
  - name: Create file for modules to install
    copy:
      dest: /etc/modules-load.d/containerd.conf
      content: |
        overlay
        br_netfilter
   
  - name: Add kernel modules 
    modprobe:
      name: "{{ item }}"
      state: present
    with_items:
    - overlay
    - br_netfilter
    
  - name: Create a file for kernel parameters
    copy:
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
      content: |
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
  
  - name: Load kernel parameters
    shell: sysctl --system

  - name: Install containerd
    apt:
      name: containerd
      state: present

  - name: Create containerd directory
    file:
      path: /etc/containerd
      state: directory
      
  - name: Copy containerd.config
    copy:
      src: config.toml
      dest: /etc/containerd/config.toml
      
  - name: Enable service containerd
    systemd:
      name: containerd
      enabled: yes     
      state: started

  - name: Download nerdctl
    get_url:
      url: https://github.com/containerd/nerdctl/releases/download/v0.16.1/nerdctl-0.16.1-linux-amd64.tar.gz
      dest: /tmp/nerdctl.tar.gz
 
  - name: Extract nerdctl into /usr/local/bin
    unarchive:
      src: /tmp/nerdctl.tar.gz
      dest: /usr/local/bin
      remote_src: yes
