---
- name: Playbook to run only master nodes.
  hosts: master
  remote_user: root
  
  tasks:
  - name: Start cluster by kubeadm
    shell: kubeadm init --pod-network-cidr=192.168.0.0/16
    ignore_errors: True
    
  - name: Add a line to a file 
    ansible.builtin.lineinfile:
      path: /etc/environment
      line: KUBECONFIG="/etc/kubernetes/admin.conf"
   
  - name: Start cluster by kubeadm
    shell: export KUBECONFIG="/etc/kubernetes/admin.conf"
    
  - name: Start cluster by kubeadm
    shell: kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml && kubectl create -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml

  - name: Generate join command
    shell: kubeadm token create --print-join-command > /tmp/kubeadm-join.sh
    register: kubeadm_join
    
  #  debug: var=kubeadm_join.stdout

