---
- name: Playbook to run only worker nodes.
  hosts: worker
  remote_user: root

  tasks:
    - name: Transfer file from ServerA to ServerB
      copy:
        src: /tmp/kubeadm-join.sh
        dest: /tmp/kubeadm-join.sh

    - name: Join the node to cluster
      command: sh /tmp/kubeadm-join.sh