#deploy nginx

- name: Get nginx ingress controller values
  copy:
    src: nginx-values.yaml
    dest: /tmp/nginx-values.yaml
    
    
- name: Install nginx chart
  kubernetes.core.helm:
    name: ingress-nginx
    namespace: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    create_namespace: yes
    values_files:
      - /tmp/nginx-values.yaml
