---
- name: Install kubernetes components 
  hosts: all
  remote_user: root
  
  tasks:
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none
      
  - name: Copy kubernetes repo
    copy:
      src: kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo

   - name: Disabling SELinux state
     selinux:
       state: disabled
       
   - name: Install these packages - kubelet kubeadm kubectl
    yum:
      name: "{{ item }}"
    with.items:  
      - kubelet
      - kubeadm
      - kubectl
      state: latest
      disable_excludes: kubernetes
