---
- name: Install containerd on CentOS
  hosts: all
  remote_user: root
  
  tasks:
  - name: Add repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: Install containerd
    yum:
      name: containerd.io
      state: present
      
  - name: Enable service containerd
    systemd:
      name: containerd
      enabled: yes     
      state: started

  - name: Download nerdctl
    get_url:
      url: https://github.com/containerd/nerdctl/releases/download/v0.16.1/nerdctl-0.16.1-linux-amd64.tar.gz
      dest: /tmp/nerdctl.tar.gz
 
  - name: Extract foo.tgz into /var/lib/foo
    unarchive:
      src: /tmp/nerdctl.tar.gz
      dest: /usr/local/bin
      remote_src: yes
