---
- hosts: all
  roles:
    - role: python
    - role: containerd
    - role: common

- hosts: master
  roles:
    - role: master

- hosts: worker
  roles:
    - role: worker
    
- hosts: master
  roles:
    - role: helm



