---
- name: Playbook to run only master nodes.
  hosts: master
  remote_user: root
  
  tasks:
  - name: Start cluster by kubeadm
    shell: kubeadm init --pod-network-cidr=192.168.0.0/16
    register: output
  
  - debug: msg="{{ output.stderr }}"
  - debug: msg="{{ output.stdout }}"
