---
- name: Playbook to run only worker nodes.
  hosts: worker, monitoring
  remote_user: root

  tasks:
  
    - name: check if join.sh exists
      stat: 
        path: /tmp/kubeadm-join.sh
      register: kelsey
  
    - name: Copy kubeadm_join command
      copy:
        src: /tmp/kubeadm-join.sh
        dest: /tmp/kubeadm-join.sh
        when: kelsey.stat.exists == false

    - name: Join the node to cluster
      command: sh /tmp/kubeadm-join.sh
      when: kelsey.stat.exists == false
