---
- name: Playbook to run only worker nodes.
  hosts: worker, monitoring
  remote_user: root

  tasks:
    - name: Copy kubeadm_join command
      copy:
        src: /tmp/kubeadm-join.sh
        dest: /tmp/kubeadm-join.sh

    - name: Join the node to cluster
      command: sh /tmp/kubeadm-join.sh
