
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none
  
  - name: Stop firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no
    when: ansible_os_family == "RedHat"

  - name: Gpg key for kube packages
    shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - 
  # Copy kubernetes repo for ubuntu
  - name: Copy kubernetes repo
    copy:
      src: kubernetes.list
      dest: /etc/apt/sources.list.d/kubernetes.list
      owner: root
      group: root
      mode: 0644
    when: ansible_os_family == "Debian"

  - name: Change hostname to {{ inventory_hostname }}
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Disabling SELinux state
    selinux:
      state: disabled
    register: selinux_status
    when: ansible_os_family == "RedHat"
    
  - name: Reboot if selinux tag changes
    reboot:
      reboot_timeout: 3600
    when: selinux_status is changed and ansible_os_family == "RedHat"

  - name: Apt update
    shell: apt update -y 
    when: ansible_os_family == "Debian"


  - name: Install kube packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - kubelet
        - kubeadm
#        - kubelet-{{ kube_version }}
        #- kubeadm-{{ kube_version }}
        - kubectl
      state: present

  - name: Enable kubelet
    systemd:
      name: kubelet
      state: started
      enabled: yes
