
  - name: Check port 6443
    shell: ss -tulnp | grep 6443
    register: port
    ignore_errors: true

  - name: Create kubeadm-config
    template:
      src: kubeadm-config.yaml.j2
      dest: /root/kubeadm-config.yaml

  - name: Create static pod directory
    file:
      path: /etc/kubernetes/manifests
      state: directory

  - name: Create kubevip-manifest
    template:
      src: kubevip-config.yaml.j2
      dest: /etc/kubernetes/manifests/kubevip.yaml


  - name: Start cluster by kubeadm
    delegate_to: "{{ groups['master'][0] }}"
    shell: kubeadm init --config /root/kubeadm-config.yaml
    when: port.stdout == ""
    register: init_cluster

  - name: Add a line to a file 
    ansible.builtin.lineinfile:
      path: /etc/environment
      line: KUBECONFIG="/etc/kubernetes/admin.conf"
   
  - name: Export kubeconfig to create resources
    shell: export KUBECONFIG="/etc/kubernetes/admin.conf"
    
  - name: Deploy calico network plugin
    shell: kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml && kubectl create -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml
    delegate_to: "{{ groups['master'][0] }}"
    when: init_cluster is not skipped

  - name: Generate join command
    shell: kubeadm token create --print-join-command > /tmp/kubeadm-join.sh
    delegate_to: "{{ groups['master'][0] }}"
    register: kubeadm_join

  - name: Fetch join.sh ( copy from master to ansible host)
    delegate_to: "{{ groups['master'][0] }}"
    fetch:
      src: /tmp/kubeadm-join.sh
      dest: /tmp/kubeadm-join.sh
      flat: yes
  
  - name: Install bashcompletion
    yum:
      name: bash-completion
      state: present


  - name: Edit .bashrc
    blockinfile: 
      state: present
      insertafter: EOF
      dest: /root/.bashrc
      content: |
        alias k=kubectl
        complete -F __start_kubectl k

        


