
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none
      
  - name: Copy kubernetes repo
    copy:
      src: kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo

  - name: Disabling SELinux state
    selinux:
      state: disabled
    register: selinux_status
    
  - name: Reboot if selinux tag changes
    reboot:
      reboot_timeout: 3600
    when: selinux_status is changed
    
  - name: Install kube packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl
      state: present

  - name: Prevent kube packages from being updated
    community.general.yum_versionlock:
      state: present
      name:
      - kubelet
      - kubeadm
      - kubectl
      
      
  - name: Enable kubelet
    systemd:
      name: kubelet
      state: started
      enabled: yes
