  
 - name: Template a file
   template:
    src: /tmp/redis-sink.yaml.j2
    dest: /tmp/redis-sink.yaml
    
    
- name: Wait for pulsar-toolset pod
  shell: kubectl get pod -n pulsar pulsar-toolset-0
  register: pod_status
  until: pod_status.stdout.find("Running") != -1
  
- name: Copy redis-sink.yaml to pod
  shell: kubectl cp /tmp/redis-sink.yaml pulsar-toolset-0:/tmp/redis-sink.yaml -n pulsar && 
  
