  
- name: Template a file
  template:
    src: redis-sink.yaml.j2
    dest: /tmp/redis-sink.yaml
 
- name: Copy first func.
  copy:
    src: firstfunc.yaml
    dest: /tmp/firstfunc.yaml
    
- name: Copy second func.
  copy:
    src: secondfunc.yaml
    dest: /tmp/secondfunc.yaml    
    
- name: Wait for pulsar-toolset pod
  shell: kubectl get pod -n pulsar pulsar-toolset-0
  register: pod_status
  until: pod_status.stdout.find("Running") != -1
  
- name: Copy firsfunc.yaml to pod and run 
  shell: kubectl cp /tmp/firstfunc.yaml pulsar-toolset-0:/tmp/firstfunc.yaml -n pulsar && /pulsar/bin/pulsar-admin functions localrun --function-config-file /tmp/firstfunc.yaml
  
- name: Copy secondfunc.yaml to pod and run 
  shell: kubectl cp /tmp/secondfunc.yaml pulsar-toolset-0:/tmp/secondfunc.yaml -n pulsar && /pulsar/bin/pulsar-admin functions localrun --function-config-file /tmp/secondfunc.yaml  
  
  
- name: Copy redis-sink.yaml to pod and run 
  shell: kubectl cp /tmp/redis-sink.yaml pulsar-toolset-0:/tmp/redis-sink.yaml -n pulsar &&  /pulsar/bin/pulsar-admin sinks localrun --sink-config-file /tmp/redis-sink.yaml
  
