initialize: true

extra:
  # Pulsar proxy
  proxy: true
  # Bookkeeper auto-recovery
  autoRecovery: false
  # Pulsar dashboard
  # Deprecated
  # Replace pulsar-dashboard with pulsar-manager
  dashboard: true
  # pulsar manager
  pulsar_manager: true

volumes:
  persistence: false

# disabled AntiAffinity
affinity:
  anti_affinity: false

# disable auto recovery
components:
  autorecovery: false

zookeeper:
  replicaCount: 1

bookkeeper:
  replicaCount: 1

broker:
  replicaCount: 1
  configData:
    ## Enable `autoSkipNonRecoverableData` since bookkeeper is running
    ## without persistence
    autoSkipNonRecoverableData: "true"
    # storage settings
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"

proxy:
  replicaCount: 
  
  
toolset:
  additionalCommand: curl https://gitlab.com/a8633/deploy-pulsar-functions/-/raw/main/pulsar-io-redis-2.9.1.nar -o /tmp/pulsar-io-redis-2.9.1.nar
